import Link from 'next/link'
import { ArticleRow } from '@/components/content/ArticleRow'
import { PodcastPlayer } from '@/components/content/PodcastPlayer'
import { listArticles, listPodcasts, listTopics } from '@/lib/knowledge'

export default async function Home() {
  const [articles, topics, podcasts] = await Promise.all([listArticles(), listTopics(), listPodcasts()])
  const featured = articles[0]
  return <main className="site-main"><section className="home-hero"><div><h1>把快速变化的 AI，整理成值得长期阅读的知识。</h1><p>我们核验来源、补足上下文，再把分散的信息整理成文章、专题和播客。</p><div className="hero-actions"><Link className="primary-button" href="/articles">浏览内容库</Link><Link className="text-link" href="/about">了解编辑原则 <span>→</span></Link></div></div><aside className="hero-note"><span>编辑说明</span><p>没有信息流焦虑，没有站内争论。这里只有经过筛选、能回查来源的内容。</p><Link href="/rss.xml">订阅 RSS</Link></aside></section>{featured ? <section className="featured-section"><header className="section-heading"><h2>今日精选</h2><span>{featured.publishedAt || '持续更新'}</span></header><article className="featured-article"><div className="featured-visual" aria-hidden="true"><span>{featured.categoryLabel}</span><strong>01</strong><i /></div><div className="featured-copy"><div className="article-meta"><span>{featured.categoryLabel}</span><span>{featured.readingMinutes} 分钟</span><span className="verified-source">来源已核验</span></div><h2><Link href={`/articles/${featured.slug}`}>{featured.title}</Link></h2><p>{featured.summary}</p><Link className="text-link" href={`/articles/${featured.slug}`}>阅读全文 <span>→</span></Link></div></article></section> : null}<section className="content-section"><header className="section-heading"><div><h2>最新内容</h2><p>按更新时间浏览编辑部最近整理的内容。</p></div><Link href="/articles">查看全部</Link></header><div className="article-list">{articles.slice(1, 6).map((article, index) => <ArticleRow key={article.slug} article={article} index={index + 1} />)}</div></section><section className="topics-home"><header className="section-heading"><div><h2>热门专题</h2><p>从一个问题出发，按顺序建立完整理解。</p></div><Link href="/topics">全部专题</Link></header><div className="topic-paths">{topics.slice(0, 4).map((topic, index) => <Link href={`/topics/${topic.slug}`} key={topic.slug}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{topic.title}</h3><p>{topic.summary}</p><small>{topic.articleCount} 篇内容 · 编号阅读路径</small></div><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6" /></svg></Link>)}</div></section>{podcasts[0] ? <section className="podcast-home"><div><h2>最新播客</h2><p>把值得展开的主题，整理成一段可以边走边听的说明。</p><Link className="text-link" href="/podcasts">查看全部节目 <span>→</span></Link></div><PodcastPlayer title={podcasts[0].title} audioUrl={podcasts[0].audioUrl} /></section> : null}<section className="community-callout"><div><h2>阅读之外，在外部社群继续交流。</h2><p>我们把讨论留在微信、飞书和 Telegram，把网站保持为安静、可检索的知识空间。</p></div><div><Link className="primary-button" href="/community">查看社群入口</Link><Link className="text-link" href="/submit">匿名提交线索 <span>→</span></Link></div></section></main>
}
