"""Add model and tool profiles."""
from alembic import op
import sqlalchemy as sa
revision="20260719_0003"; down_revision="20260719_0002"; branch_labels=None; depends_on=None
def upgrade():
    if sa.inspect(op.get_bind()).has_table("knowledge_catalog_profiles"): return
    op.create_table("knowledge_catalog_profiles", sa.Column("id",sa.Integer(),primary_key=True), sa.Column("slug",sa.String(220),nullable=False), sa.Column("name",sa.String(240),nullable=False), sa.Column("profile_type",sa.String(32),nullable=False), sa.Column("provider",sa.String(160),nullable=False,server_default=""), sa.Column("summary",sa.Text(),nullable=False,server_default=""), sa.Column("pricing",sa.String(240),nullable=False,server_default="未标注"), sa.Column("availability",sa.String(240),nullable=False,server_default="未标注"), sa.Column("context_window",sa.String(120),nullable=False,server_default="未标注"), sa.Column("capabilities",sa.Text(),nullable=False,server_default=""), sa.Column("best_for",sa.Text(),nullable=False,server_default=""), sa.Column("limitations",sa.Text(),nullable=False,server_default=""), sa.Column("latest_change",sa.Text(),nullable=False,server_default=""), sa.Column("website_url",sa.String(500)), sa.Column("api_available",sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column("open_source",sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column("status",sa.String(32),nullable=False,server_default="draft"), sa.Column("published_at",sa.DateTime()), sa.Column("verified_at",sa.DateTime()), sa.Column("created_by",sa.Integer(),sa.ForeignKey("admin_accounts.id")), sa.Column("updated_by",sa.Integer(),sa.ForeignKey("admin_accounts.id")), sa.Column("is_deleted",sa.Boolean(),nullable=False,server_default=sa.false()), sa.Column("created_at",sa.DateTime(),nullable=False), sa.Column("updated_at",sa.DateTime(),nullable=False))
    op.create_index("ix_catalog_slug","knowledge_catalog_profiles",["slug"],unique=True); op.create_index("ix_catalog_type","knowledge_catalog_profiles",["profile_type"]); op.create_index("ix_catalog_status","knowledge_catalog_profiles",["status"])
def downgrade():
    if sa.inspect(op.get_bind()).has_table("knowledge_catalog_profiles"): op.drop_table("knowledge_catalog_profiles")
