import { PlusOutlined } from '@ant-design/icons'
import { Button, Checkbox, Form, Input, Modal, Select, Space, Table, Typography, message } from 'antd'
import { useEffect, useState } from 'react'
import { adminApi } from '../api/client'
import type { CatalogProfile, CatalogProfileInput } from '../api/types'
import { StatusTag } from '../components/StatusTag'

const defaults:Partial<CatalogProfileInput>={profile_type:'model',pricing:'未标注',availability:'未标注',context_window:'未标注',api_available:false,open_source:false}
export function CatalogPage(){
 const[items,setItems]=useState<CatalogProfile[]>([]),[type,setType]=useState<string>(),[open,setOpen]=useState(false),[editing,setEditing]=useState<CatalogProfile>();const[form]=Form.useForm<CatalogProfileInput>();const[msg,holder]=message.useMessage();const load=()=>adminApi.catalog(type).then(setItems);useEffect(()=>{load()},[type])
 const edit=(x?:CatalogProfile)=>{setEditing(x);setOpen(true);form.setFieldsValue(x||defaults)};const save=async(v:CatalogProfileInput)=>{editing?await adminApi.updateProfile(editing.id,v):await adminApi.createProfile(v);msg.success(editing?'档案已更新':'档案草稿已创建');setOpen(false);form.resetFields();load()};const transition=async(x:CatalogProfile,s:string)=>{await adminApi.transitionProfile(x.id,s);load()}
 return <>{holder}<header className="page-heading"><div><Typography.Title level={2}>模型与工具档案</Typography.Title><Typography.Text type="secondary">维护价格、可用性、能力边界和变化说明。</Typography.Text></div><Button type="primary" icon={<PlusOutlined/>} onClick={()=>edit()}>新建档案</Button></header><div className="filter-bar"><Select allowClear placeholder="全部类型" value={type} onChange={setType} style={{width:140}} options={[{value:'model',label:'模型'},{value:'tool',label:'工具'}]}/></div><Table rowKey="id" dataSource={items} columns={[{title:'名称',render:(_,x)=><div className="title-cell"><strong>{x.name}</strong><small>{x.provider} · {x.summary}</small></div>},{title:'类型',dataIndex:'profile_type',width:80},{title:'价格',dataIndex:'pricing',width:160},{title:'状态',dataIndex:'status',width:90,render:v=><StatusTag status={v}/>},{title:'操作',width:260,render:(_,x)=><Space><Button onClick={()=>edit(x)}>编辑</Button><Button disabled={x.status!=='draft'} onClick={()=>transition(x,'reviewing')}>审核</Button><Button type="primary" disabled={x.status!=='reviewing'} onClick={()=>transition(x,'published')}>发布</Button></Space>}]}/><Modal title={editing?'编辑档案':'新建档案'} open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()} width={820} destroyOnHidden><Form form={form} layout="vertical" onFinish={save} initialValues={defaults}><div className="resource-form-grid"><Form.Item name="name" label="名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="slug" label="Slug" rules={[{required:true}]}><Input disabled={Boolean(editing)}/></Form.Item><Form.Item name="profile_type" label="类型"><Select disabled={Boolean(editing)} options={[{value:'model',label:'模型'},{value:'tool',label:'工具'}]}/></Form.Item><Form.Item name="provider" label="厂商"><Input/></Form.Item><Form.Item name="pricing" label="价格"><Input/></Form.Item><Form.Item name="availability" label="可用性"><Input/></Form.Item><Form.Item name="context_window" label="上下文/产品形态"><Input/></Form.Item><Form.Item name="website_url" label="官网 URL"><Input/></Form.Item></div><Form.Item name="summary" label="摘要"><Input.TextArea/></Form.Item><Form.Item name="capabilities" label="核心能力"><Input.TextArea/></Form.Item><Form.Item name="best_for" label="适合场景"><Input.TextArea/></Form.Item><Form.Item name="limitations" label="限制"><Input.TextArea/></Form.Item><Form.Item name="latest_change" label="最近变化"><Input.TextArea/></Form.Item><Space><Form.Item name="api_available" valuePropName="checked"><Checkbox>支持 API</Checkbox></Form.Item><Form.Item name="open_source" valuePropName="checked"><Checkbox>开源</Checkbox></Form.Item></Space></Form></Modal></>
}
